-- Migration: create security_events table for recorded security incidents
create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  severity text,
  details text,
  source_ip text,
  metadata jsonb,
  created_at timestamptz default now()
);
